import {
  LayoutDashboard,
  Building2,
  Users,
  Layers,
  BarChart3,
  GraduationCap,
  FileText,
  Briefcase,
  Megaphone,
  Code2,
  Brain,
  FileSearch,
  MessageSquare,
  Send,
  Target,
  Network,
  FileBarChart,
  CalendarPlus,
  UserPlus,
  Compass,
} from "lucide-react";

const item = (to, label, icon, key) => ({ to, label, icon, key });

export const roleConfig = {
  super_admin: {
    label: "Platform Control",
    role: "super_admin",
    accent: "#0a0a0a",
    sections: [
      { title: "Platform", items: [
        item("/platform", "Command", LayoutDashboard, "command"),
        item("/platform/institutions", "Institutions", Building2, "institutions"),
        item("/platform/recruiters", "Recruiter network", Network, "recruiters"),
      ]},
      { title: "Intelligence", items: [
        item("/platform/analytics", "Analytics engine", BarChart3, "analytics"),
        item("/platform/placements", "Placement layer", BarChart3, "placements"),
        item("/platform/announcements", "Broadcasts", Megaphone, "announcements"),
      ]},
      { title: "Partnership Control", items: [
        item("/platform/mou", "MOU vault", FileText, "mou"),
        item("/platform/fdp", "FDP program", GraduationCap, "fdp"),
        item("/platform/revenue", "Revenue share", BarChart3, "revenue"),
        item("/platform/reports", "Reports - exports", FileBarChart, "reports"),
        item("/platform/comm-log", "Comm logs", MessageSquare, "comm"),
        item("/platform/partner-chat", "Partner chat", MessageSquare, "chat"),
        item("/platform/workshops", "Workshops", CalendarPlus, "workshops"),
        item("/platform/benchmarking", "Benchmarking", BarChart3, "benchmarking"),
        item("/platform/team", "Team & invites", UserPlus, "team"),
      ]},
    ],
  },
  institution_admin: {
    label: "Institution Console",
    role: "institution_admin",
    accent: "#0a0a0a",
    sections: [
      { title: "Institution", items: [
        item("/institution", "Overview", LayoutDashboard, "overview"),
        item("/institution/profile", "Profile", Building2, "profile"),
        item("/institution/departments", "Departments", Users, "departments"),
        item("/institution/programs", "Training programs", Layers, "programs"),
      ]},
      { title: "Operations", items: [
        item("/institution/analytics", "Analytics engine", BarChart3, "analytics"),
        item("/institution/outcomes", "Placement intelligence", BarChart3, "outcomes"),
        item("/institution/dsa", "DSA intelligence", Code2, "dsa"),
        item("/institution/aptitude", "Aptitude intelligence", Brain, "aptitude"),
        item("/institution/ats", "Resume ATS", FileSearch, "ats"),
        item("/institution/interviews", "Interview intelligence", MessageSquare, "interviews"),
        item("/institution/team", "Team & invites", UserPlus, "team"),
        item("/institution/mou", "MOU vault", FileText, "mou"),
        item("/institution/reports", "Reports - exports", FileBarChart, "reports"),
        item("/institution/announcements", "Announcements", Megaphone, "ann"),
        item("/institution/fdp", "FDP program", GraduationCap, "fdp"),
        item("/institution/revenue", "Revenue share", BarChart3, "revenue"),
        item("/institution/partner-chat", "Partner chat", MessageSquare, "chat"),
        item("/institution/workshops", "Workshops", CalendarPlus, "workshops"),
        item("/institution/benchmarking", "Benchmarking", BarChart3, "benchmarking"),
      ]},
    ],
  },
  tpo: {
    label: "Placement Command",
    role: "tpo",
    accent: "#ff3b00",
    sections: [
      { title: "Command", items: [
        item("/tpo", "Mission control", LayoutDashboard, "overview"),
        item("/tpo/analytics", "Analytics engine", BarChart3, "analytics"),
        item("/tpo/outcomes", "Placement outcomes", BarChart3, "outcomes"),
        item("/tpo/applications", "Application pipeline", Send, "applications"),
        item("/tpo/jobs", "Active drives", Briefcase, "jobs"),
        item("/tpo/schedule", "Interview schedule", CalendarPlus, "schedule"),
      ]},
      { title: "Talent", items: [
        item("/tpo/roster", "Student roster", Users, "roster"),
        item("/tpo/cohorts", "Cohorts", Layers, "cohorts"),
        item("/tpo/training", "Training", GraduationCap, "training"),
      ]},
      { title: "Intelligence", items: [
        item("/tpo/dsa", "DSA intelligence", Code2, "dsa"),
        item("/tpo/aptitude", "Aptitude", Brain, "aptitude"),
        item("/tpo/ats", "Resume ATS", FileSearch, "ats"),
        item("/tpo/interviews", "Interview AI", MessageSquare, "interviews"),
      ]},
      { title: "Partnerships", items: [
        item("/tpo/recruiters", "Recruiter network", Network, "rec"),
        item("/tpo/team", "Team & invites", UserPlus, "team"),
        item("/tpo/mou", "MOU - partnership", FileText, "mou"),
        item("/tpo/reports", "Reports - exports", FileBarChart, "reports"),
        item("/tpo/announcements", "Broadcasts", Megaphone, "ann"),
        item("/tpo/fdp", "FDP program", GraduationCap, "fdp"),
        item("/tpo/comm-log", "Comm logs", MessageSquare, "comm"),
        item("/tpo/revenue", "Revenue share", BarChart3, "revenue"),
        item("/tpo/partner-chat", "Partner chat", MessageSquare, "chat"),
        item("/tpo/workshops", "Workshops", CalendarPlus, "workshops"),
        item("/tpo/benchmarking", "Benchmarking", BarChart3, "benchmarking"),
      ]},
    ],
  },
  faculty: {
    label: "Faculty Console",
    role: "faculty",
    accent: "#4a5d3a",
    sections: [
      { title: "Teaching", items: [
        item("/faculty", "My batches", LayoutDashboard, "overview"),
        item("/faculty/roster", "Students", Users, "roster"),
        item("/faculty/training", "Training completion", GraduationCap, "training"),
        item("/faculty/fdp", "FDP program", GraduationCap, "fdp"),
      ]},
      { title: "Analytics", items: [
        item("/faculty/analytics", "Analytics engine", BarChart3, "analytics"),
        item("/faculty/dsa", "DSA analytics", Code2, "dsa"),
        item("/faculty/aptitude", "Aptitude analytics", Brain, "aptitude"),
        item("/faculty/ats", "Resume ATS", FileSearch, "ats"),
        item("/faculty/interviews", "Interview reports", MessageSquare, "interviews"),
        item("/faculty/workshops", "Workshops", CalendarPlus, "workshops"),
        item("/faculty/benchmarking", "Benchmarking", BarChart3, "benchmarking"),
      ]},
    ],
  },
  student: {
    label: "Your Workspace",
    role: "student",
    accent: "#c1440e",
    sections: [
      { title: "Readiness", items: [
        item("/student", "Home", LayoutDashboard, "home"),
        item("/student/dsa", "DSA tracker", Code2, "dsa"),
        item("/student/aptitude", "Aptitude tracker", Brain, "aptitude"),
        item("/student/ats", "Resume ATS", FileSearch, "ats"),
        item("/student/interviews", "Interview prep", MessageSquare, "interviews"),
        item("/student/resume", "Resume builder", FileText, "resume"),
        item("/student/skill-gap", "Skill gap analysis", Target, "skill-gap"),
        item("/student/ai-analysis", "AI analysis", Brain, "ai-analysis"),
      ]},
      { title: "Opportunities", items: [
        item("/student/jobs", "Open drives", Briefcase, "jobs"),
        item("/student/applications", "My applications", Send, "apps"),
        item("/student/schedule", "Interview slots", CalendarPlus, "schedule"),
        item("/student/announcements", "Announcements", Megaphone, "ann"),
        item("/student/career", "Career recommendations", Compass, "career"),
      ]},
    ],
  },
  recruiter: {
    label: "Recruiter Console",
    role: "recruiter",
    accent: "#1a1a1a",
    sections: [
      { title: "Hiring", items: [
        item("/recruiter", "Overview", LayoutDashboard, "overview"),
        item("/recruiter/jobs", "Open roles", Briefcase, "jobs"),
        item("/recruiter/talent", "Talent pool", Target, "talent"),
        item("/recruiter/schedule", "Interview schedule", CalendarPlus, "schedule"),
        item("/recruiter/applications", "Pipeline", Send, "apps"),
        item("/recruiter/analytics", "Hiring intelligence", BarChart3, "analytics"),
      ]},
    ],
  },
};
